# Generated by Django 4.0.5 on 2022-07-03 14:07

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('top_moments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thetop',
            name='text',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thetop',
            name='top',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='top_moments.top'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thetop',
            name='video',
            field=embed_video.fields.EmbedVideoField(default=1),
            preserve_default=False,
        ),
    ]
