# Generated by Django 4.0.5 on 2022-07-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_moments', '0003_rename_video_thetop_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='thetop',
            name='image',
            field=models.ImageField(default=1, upload_to='image/'),
            preserve_default=False,
        ),
    ]
