# Generated by Django 4.0.5 on 2022-07-06 10:15

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('top_moments', '0005_thetop_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thetop',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='thetop',
            name='name',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='thetop',
            name='text',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='thetop',
            name='top',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='top_moments.top'),
        ),
        migrations.AlterField(
            model_name='thetop',
            name='url',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
