# Generated by Django 4.0.5 on 2022-07-07 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_moments', '0006_alter_thetop_image_alter_thetop_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thetop',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/top_moments/images/'),
        ),
        migrations.AlterField(
            model_name='thetop',
            name='name',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
