# Generated by Django 4.0.5 on 2022-07-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_moments', '0008_alter_thetop_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thetop',
            name='image',
            field=models.ImageField(blank=True, upload_to='A:/Python_projects/konoha/konoha/konoha/top_moments/static/top_moments/images/'),
        ),
    ]
