# Generated by Django 4.0.5 on 2022-07-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_moments', '0011_remove_thetop_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='thetop',
            name='text',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
